# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
#
is_cloud_environment: yes
provider: aws
availability_zone: eu-west-1a
region_id: eu-west-1
security_group_id: sg-0751b1a72bd251609
subnet_id: subnet-051a7af6dbab85cc9
