# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Check if disks already exist
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk_info:
    name: "{{ vm_name }}_{{ item.disk_name }}"
    resource_group: "{{ resource_group }}"
  register: r_azure_rm_manageddisk_info
  with_items: "{{ volumes }}"

- debug: var=r_azure_rm_manageddisk_info
  delegate_to: localhost
  when: debug | bool

- name: Create and attach the managed disk to VM
  delegate_to: localhost
  azure.azcollection.azure_rm_manageddisk:
    name: "{{ vm_name }}_{{ item.disk_name }}"
    resource_group: "{{ resource_group }}"
    disk_size_gb: "{{ item.size_GB }}"
    managed_by: "{{ vm_name }}"
    os_type: "{{ os_type }}"
    storage_account_type: "{{ storage_account_type }}"
  register: r_azure_rm_manageddisk
  when: r_azure_rm_manageddisk_info|json_query('results[*].ansible_info.azure_managed_disk[*].name[]|[?contains(@, `'+vm_name+'_'+item.disk_name+'`) == `true`]')|length==0
  with_items: "{{ volumes }}"

- debug: var=r_azure_rm_manageddisk
  delegate_to: localhost
  when: debug | bool
