# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Create volume
  delegate_to: localhost
  oracle.oci.oci_blockstorage_volume:
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ availability_domain }}"
    display_name: "{{ vm_name }}_{{ item.volume_name }}"
    size_in_gbs: "{{ item.size_GB }}"
    freeform_tags : "{{ custom_tags }}"
  with_items: "{{ volumes }}"
  register: r_oci_blockstorage_volume_present

- debug: var=r_oci_blockstorage_volume_present
  delegate_to: localhost
  when: debug | bool

- name: Get instances ID
  delegate_to: localhost
  oracle.oci.oci_compute_instance_facts:
    compartment_id: "{{ compartment_id }}"
    availability_domain: "{{ availability_domain }}"
    display_name: "{{ vm_name }}"
    lifecycle_state: RUNNING
  register: r_oci_compute_instance_facts
  failed_when: r_oci_compute_instance_facts.instances|length == 0

- debug: var=r_oci_compute_instance_facts
  delegate_to: localhost
  when: debug | bool

- name: Create volume attachment
  delegate_to: localhost
  oracle.oci.oci_compute_volume_attachment:
    compartment_id: "{{ compartment_id }}"
    type: iscsi
    instance_id: "{{ r_oci_compute_instance_facts.instances[0].id }}"
    volume_id: "{{ item.volume.id }}"
  with_items: "{{ r_oci_blockstorage_volume_present.results }}"
  register: r_oci_blockstorage_volume_attachment

- debug: var=r_oci_blockstorage_volume_attachment
  delegate_to: localhost
  when: debug | bool
