# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Get the list of existing instances
  delegate_to: localhost
  community.aws.ec2_instance_info:
    region: "{{ region_id }}"
    filters:
      "tag:Name": "{{ vm_name }}"
      instance-state-name: [ "pending", "running", "shutting-down", "stopping", "stopped" ]
  register: r_aws
  failed_when: r_aws.instances|length != 1

- debug: var=r_aws
  delegate_to: localhost
  when: debug | bool

- name: Create and attach the volumes to instance
  delegate_to: localhost
  amazon.aws.ec2_vol:
    region: "{{ region_id }}"
    instance: "{{ r_aws.instances[0].instance_id }}"
    volume_size: "{{ item.size_GB }}"
    volume_type: "{{ item.disk_type }}"
    device_name: "{{ item.device_name }}"
    delete_on_termination: yes
    tags: "{{ {'Name': item.device_name} | combine(custom_tags) }}"
  register: r_aws_vol
  with_items: "{{ volumes }}"
