stages:
- test
- build

variables:
  CI_PRE_CLONE_SCRIPT: umask 0022

build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${TAG}" .
    - docker tag "$CI_REGISTRY_IMAGE:${TAG}" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:${TAG}"
    - docker push "$CI_REGISTRY_IMAGE:${STATUS_TAG}"
  # Run this job on tag creation and when a Dockerfile exists
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      variables:
        TAG: $CI_COMMIT_TAG
        STATUS_TAG: latest
      - if: $CI_COMMIT_TAG =~ /^[0-9]*\.[0-9]*\.[0-9]-STABLE$/
      variables:
        TAG: $CI_COMMIT_TAG
        STATUS_TAG: stable

      exists:
        - Dockerfile

