stages:
  - local_debug
  - lint
  - build_vm_infra
  - destroy_vm_infra
  - build

variables:
  CI_PRE_CLONE_SCRIPT: umask 0022
  TARGET: "aws"
  CLOUD: "AWS"

lint:
  stage: lint
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - pwd
    - ansible-lint --version
    - ansible-lint --show-relpath --config-file gitlab_ci/ansible-lint.yml
  allow_failure: true

dbg:
  stage: local_debug
  image: busybox:latest
  script:
    - env

include: 
  - project: 'dbiservices/yak/yak_dev_infrastructure'
    ref: add_ci
    file: 'build_vm_infra.yml'
  - project: 'dbiservices/yak/yak_dev_infrastructure'
    ref: add_ci
    file: 'destroy_vm_infra.yml'

build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${TAG}" --build-arg CI_COMMIT_TAG=${CI_COMMIT_TAG} --build-arg CI_COMMIT_SHORT_SHA=${CI_COMMIT_SHORT_SHA} --build-arg YAKENV_TAG=${YAKENV_TAG} .
    - docker tag "$CI_REGISTRY_IMAGE:${TAG}" "$CI_REGISTRY_IMAGE:${MAIN_TAG}" 
    - docker push "$CI_REGISTRY_IMAGE:${TAG}"
    - docker push "$CI_REGISTRY_IMAGE:${MAIN_TAG}"
  # Run this job on tag creation and when a Dockerfile exists
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+-(integration|INTEGRATION)[0-9]*$/
      variables:
        TAG: $CI_COMMIT_TAG
        MAIN_TAG: integration
        YAKENV_TAG: $MAIN_TAG
      exists:
        - Dockerfile
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+-(stable|STABLE)[0-9]*$/
      variables:
        TAG: $CI_COMMIT_TAG
        MAIN_TAG: stable
        YAKENV_TAG: $MAIN_TAG
      exists:
        - Dockerfile
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+-(beta|BETA)[0-9]*$/
      variables:
        TAG: $CI_COMMIT_TAG
        MAIN_TAG: beta
        YAKENV_TAG: $MAIN_TAG
      exists:
        - Dockerfile

