stages:
- build

build:
  # Use the official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "${NEXUS_USER}" -p "${NEXUS_PASSWORD}" https://packages.dbi-services.com:9001/repository/yak-registry/
  script:
    - docker build --pull -t "packages.dbi-services.com:9001/repository/yak-registry/yak:${TAG}" .
    - docker push "packages.dbi-services.com:9001/repository/yak-registry/yak:${TAG}"
  # Run this job in a branch where a Dockerfile exists
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]*\.[0-9]*\.[0-9]*(_beta[0-9]+)*$/
      variables:
        TAG: $CI_COMMIT_TAG
      exists:
        - Dockerfile
