# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Wait for the OS to be reachable by YaK
  ansible.builtin.wait_for_connection:
    delay: 60
    timeout: 600
  vars:
    ansible_host: "{{ administrative_ip }}"

- name: Return facts to playbook
  delegate_to: localhost
  set_fact:
    returned:
      instance: "{{ r_oci_compute_instance_facts.instances[0] }}"
      administrative_ip: "{{ administrative_ip|default('none')  }}"
      private_ip_address: "{{ oci_private_ip|default('none')  }}"
      public_ip_address: "{{ oci_public_ip|default('none') }}"
      os_admin_username: "{{ os_admin_username|default('none') }}"
      os_admin_password: "{{ os_admin_password|default('none') }}"
