# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Get OCI instances facts
  delegate_to: localhost
  oracle.oci.oci_compute_instance_facts:
    compartment_id: "{{ compartment_id }}"
    display_name: "{{ display_name }}"
    lifecycle_state: STOPPED
  register: r_oci_compute_instance_facts
  failed_when: r_oci_compute_instance_facts.instances|length != 1

- name: Start instance
  delegate_to: localhost
  oracle.oci.oci_compute_instance_actions:
    compartment_id: "{{ compartment_id }}"
    instance_id: "{{ r_oci_compute_instance_facts.instances[0].id }}"
    action: start
    action_type: softreset

- name: Wait for SSH to come up
  wait_for_connection:
  when: os_type == 'linux'

- name: Wait for the WinRM port to come online
  delegate_to: localhost
  wait_for:
    port: 5986
    host: "{{ ansible_host }}"
    timeout: 600
  when: os_type == 'windows'
