# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
# vars file for artifacts
local_artifacts_path: "{{ artifacts.variables.path|default('/yak_local_storage') }}"
