# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- include_tasks: create_nic.yml

- name: Create the VM
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ server_name }}"
    short_hostname: "{{ server_name }}"
    admin_username: "{{ os_admin_username }}"
    vm_size: "{{ vm_size }}"
    virtual_network_name: "{{ virtual_network_name }}"
    subnet_name: "{{ subnet_name }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ os_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ lookup('file', ssh_public_key) }}"
    network_interfaces: "{{ server_name }}-nic001"
    image:
      offer: "{{ image.offer }}"
      publisher: "{{ image.publisher }}"
      sku: "{{ image.sku }}"
      version: "{{ image.version }}"
    os_type: "{{ os_type | capitalize }}"
    managed_disk_type: "{{ managed_disk_type }}"
    tags: "{{ custom_tags }}"
  register: r_azure

- debug: var=r_azure
  delegate_to: localhost
  when: debug | bool

- delegate_to: localhost
  set_fact:
    returned:
      instance: "{{ r_azure.ansible_facts.azure_vm }}"