# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Power On
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ server_name }}"

- name: Wait for SSH to come up
  wait_for_connection:
  when: os_type == 'linux'

- name: Wait for the WinRM port to come online
  delegate_to: localhost
  wait_for:
    port: 5986
    host: "{{ ansible_host }}"
    timeout: 600
  when: os_type == 'windows'
