# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
# defaults file for aws
state: started
os_type: linux
os_admin_username: ec2-user
server_name: "test-srv-01"
ec2_key_name: "{{ server_name }}"
ec2_instance_base_directory: "~/.{{ server_name }}"
nb_instances: 1
debug: False
returned: ""
custom_tags: {}
# ami:
#     name: "debian-11-amd64-*"
#     owner_id: 136693071363
#     image_id: '*'
force: False # If the instance exists, delete it before creating it
instance_type: t3.large
region_id: eu-central-1
availability_zone: eu-central-1a
local_ssh_key:
    path: ~/.ssh
    private_key_name: id_rsa
    public_key_name: id_rsa.pub