# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
# defaults file for aws
state: started
os_type: linux
os_admin_username: ec2-user
server_name: "test-srv-01"
root_device_name: /dev/sda1
debug: False
returned: ""
custom_tags: {}
instance_type: t3.large
region_id: eu-central-1
availability_zone: eu-central-1a
local_ssh_key:
    path: ~/.ssh
    private_key_name: id_rsa
    public_key_name: id_rsa.pub