# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Install PowerShell module AWS Tool packages
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: runas
  community.windows.win_psmodule:
    name: AWS.Tools.Installer
    state: present
    accept_license: Yes

- name: Download artifact
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: runas
  ansible.windows.win_powershell:
    script: >
      Copy-S3Object -BucketName "{{ artifacts.variables.bucket_name }}" -Key "{{ artifact_file }}" -LocalFile "{{ destination_path }}/{{ artifact_file|basename }}"
  environment:
      AWS_ACCESS_KEY_ID     : "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY : "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      AWS_SESSION_TOKEN     : "{{ lookup('env','AWS_SESSION_TOKEN') }}"
  register: r_copy_s3object
  failed_when: r_copy_s3object.error|length > 0
...
