# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- include_role:
    name: yak.core.aws_infrastructure
  vars:
    state: present
