# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Start server
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    debug: false
  tasks:

    - include_tasks: "start/{{ provider }}.yml"
