# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Stop server
  hosts: "{{ target }}"
  gather_facts: no
  vars:
    debug: false
  tasks:

    - name: Update server state
      delegate_to: localhost
      yak.core.yak_inventory_update:
        server_name: "{{ target }}"
        server_state: stopping
      when: yak_inventory_type == "database"

    - include_tasks: "stop/{{ provider }}.yml"

    - name: Update server state
      delegate_to: localhost
      yak.core.yak_inventory_update:
        server_name: "{{ target }}"
        server_state: stopped
      when: yak_inventory_type == "database"
