# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Reboot server
  become: true
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible after OS update"
    reboot_timeout: 600 # wait maximum 10 minutes for a successful connection after the reboot
    test_command: uptime
...