# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
- include_role:
    name: yak.core.oci_compute
  vars:
    state: present
    region: "{{ region_id }}"
    display_name: "{{ machine_name }}"
    ssh_public_key: "{{ ansible_ssh_public_key_file }}"
    ssh_private_key: "{{ ansible_ssh_private_key_file }}"
    winrm_cert_pem_path: "{{ ansible_winrm_cert_pem }}"
    winrm_user: "{{ ansible_user }}"
    os_admin_username: "{{ ansible_user }}"
