# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- block:
  - name: Update yak inventory
    delegate_to: localhost
    yak.core.yak_inventory_update:
      target: "{{ inventory_hostname }}"
      private_ip: "{{ returned.private_ip_address|default(None) }}"
      public_ip: "{{ returned.public_ip_address|default(None) }}"
    when: yak_inventory_type == 'file'

  - debug:
      msg:
        - "The instance is ready. Connection details:"
        - "  administrative_ip: {{ administrative_ip }}"
        - "  private_ip: {{ returned.private_ip_address }}"
        - "  public_ip: {{ returned.public_ip_address }}"

  - debug:
      msg:
        - "  Windows user/password: {{ returned.os_admin_username }}/{{ returned.os_admin_password }}"
    when: os_type == 'windows'
  when: returned.private_ip_address is defined
...