# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Install OCI cli from PowerShell
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: runas
  ansible.windows.win_powershell:
    script: >
      Set-ExecutionPolicy RemoteSigned
      [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
      Invoke-WebRequest https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.ps1 -OutFile install.ps1
      ./install.ps1 -AcceptAllDefaults

- name: Copy Key File
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('env','OCI_USER_KEY_FILE') }}"
    dest: "C:\Users\{{ ansible_user }}\oci_key"

- name: Download artifact
  become: yes
  become_user: "{{ ansible_user }}"
  become_method: runas
  ansible.windows.win_powershell:
    script: >
      oci os object get --namespace "{{ artifacts.variables.namespace_name }}" --bucket-name "{{ artifacts.variables.bucket_name }}" --name "{{ item }}" --file "{{ destination_path }}/{{ item }}"
  environment:
      OCI_ANSIBLE_AUTH_TYPE  : "{{ lookup('env','OCI_ANSIBLE_AUTH_TYPE') }}"
      OCI_USER_ID            : "{{ lookup('env','OCI_USER_ID') }}"
      OCI_USER_FINGERPRINT   : "{{ lookup('env','OCI_USER_FINGERPRINT') }}"
      OCI_TENANCY            : "{{ lookup('env','OCI_TENANCY') }}"
      OCI_REGION             : "{{ lookup('env','OCI_REGION') }}"
      OCI_USER_KEY_FILE      : "C:\Users\{{ ansible_user }}\oci_key"
  register: r_copy_s3object
  failed_when: r_copy_s3object.error|length > 0
  loop: "{{ artifact_files }}"
...
