# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Define hostname to {{ host_name }}
  become: yes
  hostname:
    name: "{{ host_name }}"

- name: Update /etc/hosts with ansible_fqdn
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ host_name }} {{ host_name }}.{{ domain_name }}"
    state: present

- name: Set timezone to {{ time_zone }}
  become: yes
  timezone:
    name: "{{ time_zone }}"

- name: Install LVM
  become: yes
  ansible.builtin.dnf:
    name: lvm2
    state: present
  when:
    - ansible_distribution == "RedHat" or ansible_distribution == "OracleLinux"
    - ansible_distribution_major_version|int > 7
  register: r_dnf
  ignore_errors: yes # Error handled in the next step

- debug: var=r_dnf
  when: debug|bool

- name: Error handling for issues 74
  ansible.builtin.fail:
    msg: >
      Package server is not reachable, or certificate from package server is not valid.
      More info on https://gitlab.com/yak4all/yak/-/issues/74
  when: "'Cannot download repomd.xml' in r_dnf.msg"

- name: Error handling for any other issues
  ansible.builtin.fail:
    msg: "Error with task 'Install LVM': {{ r_dnf }}"
  when: r_dnf.rc > 0

- name: Update cache (Debian only) # required for LVM and XFS packages installation
  become: yes
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install LVM
  become: yes
  package:
    name: 'lvm*'
    state: present
  when: >
    (
      ( ansible_os_family == "Suse" ) or
      ( ansible_os_family == "Debian" )
    )

- name: Install XFS
  become: yes
  package:
    name: 'xfsprogs'
    state: present
  when: >
    (
      ( ansible_os_family == "RedHat" ) or
      ( ansible_os_family == "Suse" ) or
      ( ansible_os_family == "Debian" )
    ) and ansible_distribution_major_version|int > 7
...