# Copyright: (c) 2023, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Define hostname to {{ host_name }}
  ansible.windows.win_hostname:
    name: "{{ host_name }}"
  register: r_win_hostname

- name: Rebooting to take configuration into account
  ansible.windows.win_reboot:
  when: r_win_hostname.reboot_required

- name: Set timezone to {{ time_zone }} (not reboot needed)
  community.windows.win_timezone:
    timezone: "{{ time_zone }}"
  register: r_win_timezone
