---
- name: Change artifacts ownership and group
  become: true
  ansible.builtin.file:
    path: "{{ destination_path }}/{{ item|basename }}"
    owner: "{{ destination_owner }}"
    group: "{{ destination_group }}"
  loop: "{{ artifact_files }}"
...