---
- name: Creates directory layout
  become: true
  ansible.builtin.file:
    path: "{{ destination_path }}/{{ item|dirname }}"
    state: directory
    owner: "{{ destination_owner }}"
    group: "{{ destination_group }}"
    mode: 0755
    recurse: yes
  loop: "{{ artifact_files }}"
...