# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Include tasks for Artifacts provider {{ pv_artifacts_repo.provider }}
  include_tasks: "{{ ansible_system | lower }}_{{ pv_artifacts_repo.provider }}.yml"
...
