# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Include vars for artifact provider {{ artifact_provider }}
  ansible.builtin.include_vars:
    file: "{{ artifact_provider }}.yaml"
    name: stuff

- name: Include tasks for OS {{ os_type }} with artifact provider {{ artifact_provider }}
  include_tasks: "{{ artifact_provider }}/{{ os_type }}.yml"
...
