# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
- name: Role needs some variables
  ansible.builtin.assert:
    that:
      - artifacts.provider is defined
      - artifacts.variables is defined
      - artifact_files is defined
      - destination_path is defined
      - destination_owner is defined
      - destination_group is defined
    fail_msg: "Variables not properly set. Please, check instructions in the README.md file of the role."
    success_msg: "Variables variable properly set."

- name: Include pre tasks for OS {{ os_type }}
  include_tasks: "{{ os_type }}_pre.yml"

- name: Include tasks for OS {{ os_type }} with artifact provider {{ artifacts.provider }}
  include_tasks: "{{ artifacts.provider }}/{{ os_type }}.yml"

- name: Include post tasks for OS {{ os_type }}
  include_tasks: "{{ os_type }}_post.yml"
...
