# Copyright: (c) 2022, dbi services, distributed without any warranty under the terms of the GNU General Public License v3
---
# tasks file for artifacts
- name: Add PowerShell module AWS Tool packages
  community.windows.win_psmodule:
    name: AWS.Tools.Installer
    state: present

- name: Set AWS keys variables at once (but expires after a while)
  ansible.windows.win_environment:
    level: user
    variables:
      AWS_ACCESS_KEY_ID     : "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
      AWS_SECRET_ACCESS_KEY : "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
      AWS_SESSION_TOKEN     : "{{ lookup('env','AWS_SESSION_TOKEN') }}"

- name: Validate S3 bucket connection (Validate credentials)
  ansible.windows.win_powershell:
    script: |
      Test-S3Bucket -BucketName "{{ pv_artifacts_repo.bucket_name }}"
  register: reg_test_connection
  changed_when: false
  failed_when: reg_test_connection.error | length > 0

- name: Create Temp directory "{{ pv_artifacts_repo.path }}"
  ansible.windows.win_file:
    path: "{{ pv_artifacts_repo.path }}"
    state: directory

- name: Check if files have been already downloaded (not available in native AWS tools)
  ansible.windows.win_stat:
    path: "{{ pv_artifacts_repo.path }}\\{{ item }}"
  loop: "{{ pv_artifacts_list }}"
  register: reg_file_local_info

- name: Download files
  ansible.windows.win_powershell:
    script: |
      Copy-S3Object -BucketName "{{ pv_artifacts_repo.bucket_name }}" -Key "{{ item.0 }}" -LocalFolder "{{ pv_artifacts_repo.path }}"
  when: (not item.1.stat.exists)
  loop: "{{ pv_artifacts_list | zip(reg_file_local_info.results) | list }}"
  loop_control:
    label: "{{ pv_artifacts_repo.path }}/{{ item.0 }}"
...
