---
- name: Change artifacts permissions
  ansible.windows.win_acl:
    path: "{{ destination_path }}/{{ item|basename }}"
    user: "{{ destination_owner }}"
    rights: FullControl
    type: allow
    state: present
    inherit: ContainerInherit, ObjectInherit
    propagation: 'None'
  loop: "{{ artifact_files }}"
...